---

require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'lib/template.erb'

# I'm a bit more lax with Rubocop than normal.

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 25
