# frozen_string_literal: true

source 'https://rubygems.org'

gem 'minitest', '~> 5.20'
gem 'rake', '~> 13.0'
gem 'rubocop', '~> 1.57'
gem 'rubocop-minitest', '0.33'
gem 'rubocop-performance', '1.19'
gem 'rubocop-rake', '0.6'
