# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.1'

gem 'minitest', '5.16.3'
gem 'rake', '~> 13.0.6'
gem 'rubocop', '~> 1.39.0'
gem 'rubocop-minitest', '0.23.1'
gem 'rubocop-performance', '1.15.0'
gem 'rubocop-rake', '0.6.0'
