#!/usr/bin/env ruby

# frozen_string_literal: true

RUNNER = true

require_relative 'lib/runner'

def years
  Pathname.new(__dir__).children.map { |f| f.basename.to_s }
          .select { |d| d.match(/^aoc\d\d$/) }
          .map { |d| d.sub('aoc', '20') }
end

def year(year)
  ('01'..'25').map { |d| [year, d] }
end

puzzles = case ARGV.size
          when 0
            years.flat_map { |y| year y }
          when 1
            year ARGV[0]
          when 2, 3
            [ARGV]
          else
            abort 'usage: solve [year] [day] [part]'
          end

puzzles.sort.each do |p|
  Runner.new(p[0], p[1], p[2].to_i).solve_and_print!
end
